version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: notification_db
    env_file:
      - .env
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: notification_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  asynqmon:
    image: hibiken/asynqmon
    container_name: notification_asynqmon
    ports:
      - "${ASYNQMON_PORT:-8081}:8080"
    command: ["--redis-addr=redis:6379"]
    depends_on:
      - redis
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: notification_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    # extra_hosts is CRITICAL for Linux. It allows the Docker container to scrape our Go app running directly on localhost!
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: notification_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  pgdata:
  prometheus_data:
  grafana_data:
